# Generated by Django 5.0.4 on 2024-05-06 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='message_sent',
        ),
    ]
