# Generated by Django 4.1.13 on 2024-05-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_author_message_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='message_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tag',
            field=models.CharField(max_length=150),
        ),
    ]
