# Generated by Django 4.1.13 on 2024-05-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_tag_remove_quote_tag_quote_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tags',
            new_name='tag',
        ),
    ]
